from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[1]
BASELINE_DIR = BASE_DIR / "data" / "baseline"

HIGHER_BETTER = "higher_better"
LOWER_BETTER = "lower_better"


def percentile_column(metric):
    return f"{metric}_seoul_percentile"


def score_column(metric):
    return f"{metric}_seoul_score"


def metric_config(
    *,
    label,
    file,
    required_columns,
    primary_metric,
    direction,
    display_metric_label,
    json_columns=None,
    radius_rules=None,
    percentile_enabled=True,
    ranking_enabled=True,
    validation_enabled=True,
    debug_columns=None,
):
    return {
        "label": label,
        "path": str(BASELINE_DIR / file),
        "file": file,
        "required_columns": required_columns,
        "primary_metric": primary_metric,
        "primary_percentile_column": percentile_column(primary_metric),
        "primary_score_column": score_column(primary_metric),
        "display_metric_label": display_metric_label,
        "metrics": {
            primary_metric: direction,
        },
        "json_columns": json_columns or [],
        "radius_rules": radius_rules or [],
        "percentile_enabled": percentile_enabled,
        "ranking_enabled": ranking_enabled,
        "validation_enabled": validation_enabled,
        "debug_columns": debug_columns or [],
    }


BASELINE_METRIC_CONFIG = {
    "subway": metric_config(
        label="지하철",
        file="subway_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "subway_line_count_500m"],
        primary_metric="subway_line_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="가장 가까운 지하철역 거리",
        json_columns=["subway_items_500m_json", "subway_items_json"],
        radius_rules=[
            ("subway_station_count_500m", "subway_station_count_800m"),
            ("subway_station_count_800m", "subway_station_count_1km"),
        ],
    ),
    "bus": metric_config(
        label="버스",
        file="bus_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "bus_stop_count_500m", "bus_route_count"],
        primary_metric="bus_route_count",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 이용 가능 버스 노선 수",
        json_columns=["bus_items_json"],
        radius_rules=[("bus_stop_count_300m", "bus_stop_count_500m")],
    ),
    "bike": metric_config(
        label="따릉이",
        file="bike_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "bike_station_count_500m"],
        primary_metric="bike_station_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 따릉이 대여소 수",
        json_columns=["bike_items_json"],
    ),
    "convenience": metric_config(
        label="편의점",
        file="convenience_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "convenience_count_500m"],
        primary_metric="convenience_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 편의점 수",
        json_columns=["convenience_items_json"],
        radius_rules=[("convenience_count_300m", "convenience_count_500m")],
    ),
    # 마트 3개 카테고리(같은 mart_baseline.csv를 공유, 그룹별 반경/지표가 다름).
    "large_mart": metric_config(
        label="대형마트",
        file="mart_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "large_mart_count_3000m"],
        primary_metric="large_mart_count_3000m",
        direction=HIGHER_BETTER,
        display_metric_label="3km 내 대형마트(이마트·홈플러스·롯데마트) 수",
        json_columns=["large_mart_items_json"],
    ),
    "super_mart": metric_config(
        label="슈퍼마켓",
        file="mart_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "super_mart_count_500m"],
        primary_metric="super_mart_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="도보권 500m 내 슈퍼마켓 수",
        json_columns=["super_mart_items_json"],
    ),
    "warehouse_mart": metric_config(
        label="창고형마트",
        file="mart_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "warehouse_mart_count_5000m"],
        primary_metric="warehouse_mart_count_5000m",
        direction=HIGHER_BETTER,
        display_metric_label="5km 내 창고형마트(코스트코·트레이더스) 수",
        json_columns=["warehouse_mart_items_json"],
    ),
    "cafe": metric_config(
        label="카페",
        file="cafe_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "cafe_count_500m", "franchise_total_500m", "cafe_access_score_raw"],
        primary_metric="cafe_access_score_raw",
        direction=HIGHER_BETTER,
        display_metric_label="카페 접근성(프랜차이즈 수 + 브랜드 다양성)",
        json_columns=["cafe_items_json"],
        radius_rules=[("cafe_count_300m", "cafe_count_500m")],
    ),
    "medical": metric_config(
        label="의료 접근성",
        file="medical_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "medical_count_1km", "hospital_count_500m"],
        primary_metric="medical_count_1km",
        direction=HIGHER_BETTER,
        display_metric_label="1km 내 의료시설 수",
        json_columns=[
            "medical_items_json",
            "hospital_items_json",
            "emergency_items_json",
            "superior_hospital_items_json",
            "pharmacy_items_json",
        ],
        radius_rules=[
            ("medical_count_500m", "medical_count_1km"),
            ("hospital_count_500m", "hospital_count_1km"),
            ("emergency_count_1km", "emergency_count_3km"),
            ("pharmacy_count_500m", "pharmacy_count_1km"),
        ],
    ),
    "lifestyle_food": metric_config(
        label="생활편의 식음료",
        file="lifestyle_food_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "lifestyle_food_count_500m"],
        primary_metric="lifestyle_food_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 식음료 편의시설 수",
        json_columns=["lifestyle_food_items_json"],
        radius_rules=[("lifestyle_food_count_500m", "lifestyle_food_count_1km")],
        percentile_enabled=False,
        ranking_enabled=False,
    ),
    "academy": metric_config(
        label="학원",
        file="academy_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "academy_count_1000m"],
        primary_metric="academy_count_1000m",
        direction=HIGHER_BETTER,
        display_metric_label="1km 내 학원 수",
        json_columns=["academy_items_json"],
        radius_rules=[("academy_count_500m", "academy_count_1000m")],
    ),
    "culture": metric_config(
        label="문화생활",
        file="culture_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "culture_count_1500m"],
        primary_metric="culture_count_1500m",
        direction=HIGHER_BETTER,
        display_metric_label="1.5km 내 문화시설 수",
        json_columns=["culture_items_json"],
    ),
    "shopping": metric_config(
        label="쇼핑",
        file="shopping_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "shopping_count_3km"],
        primary_metric="shopping_count_3km",
        direction=HIGHER_BETTER,
        display_metric_label="3km 내 쇼핑시설 수",
        json_columns=["shopping_items_json"],
    ),
    "commercial": metric_config(
        label="상권",
        file="commercial_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "commercial_count_1km"],
        primary_metric="commercial_count_1km",
        direction=HIGHER_BETTER,
        display_metric_label="1km 내 상권 수",
        json_columns=["commercial_items_json"],
    ),
    "nightlife": metric_config(
        label="유흥시설",
        file="nightlife_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "nightlife_count_500m"],
        primary_metric="nightlife_count_500m",
        direction=LOWER_BETTER,
        display_metric_label="500m 내 유흥시설 수",
        json_columns=["nightlife_items_json"],
        radius_rules=[("nightlife_count_500m", "nightlife_count_1km")],
    ),
    "hangang": metric_config(
        label="한강공원",
        file="hangang_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "nearest_hangang_distance"],
        primary_metric="nearest_hangang_distance",
        direction=LOWER_BETTER,
        display_metric_label="가장 가까운 한강공원 거리",
        json_columns=["hangang_items_json"],
    ),
    "fire_station": metric_config(
        label="119 안전",
        file="fire_station_baseline.csv",
        required_columns=["name", "gu", "dong", "nearest_fire_station_distance"],
        primary_metric="nearest_fire_station_distance",
        direction=LOWER_BETTER,
        display_metric_label="가장 가까운 119 안전시설 거리",
        json_columns=["fire_station_items_json"],
    ),
    "ev_charger": metric_config(
        label="전기차 충전",
        file="ev_charger_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "ev_charger_count_500m"],
        primary_metric="ev_charger_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 충전소 수",
        json_columns=["ev_charger_items_json"],
        radius_rules=[
            ("ev_charger_count_300m", "ev_charger_count_500m"),
            ("ev_charger_count_500m", "ev_charger_count_1km"),
        ],
    ),
    "cctv": metric_config(
        label="CCTV",
        file="cctv_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "cctv_count_500m"],
        primary_metric="cctv_count_500m",
        direction=HIGHER_BETTER,
        display_metric_label="500m 내 CCTV 수",
        radius_rules=[("cctv_count_300m", "cctv_count_500m")],
    ),
    "park": metric_config(
        label="공원",
        file="park_baseline.csv",
        required_columns=["name", "gu", "dong", "lat", "lng", "park_distance"],
        primary_metric="park_distance",
        direction=LOWER_BETTER,
        display_metric_label="가장 가까운 공원 거리",
    ),
    "school_zone": metric_config(
        label="교육환경",
        file="school_zone_baseline.csv",
        required_columns=[
            "name",
            "gu",
            "dong",
            "lat",
            "lng",
            "assigned_elementary_school",
            "assigned_elementary_distance_m",
            "elementary_access_score",
        ],
        primary_metric="elementary_access_score",
        direction=HIGHER_BETTER,
        display_metric_label="배정초 접근 점수",
        percentile_enabled=True,
        ranking_enabled=True,
        debug_columns=[
            "assigned_elementary_school",
            "assigned_elementary_distance_m",
        ],
    ),
    "transaction_summary": metric_config(
        label="실거래 요약",
        file="transaction_summary.csv",
        required_columns=[
            "name",
            "kapt_code",
            "gu",
            "dong",
            "trade_count_1y",
            "rent_count_1y",
            "data_confidence",
        ],
        primary_metric="trade_count_1y",
        direction=HIGHER_BETTER,
        display_metric_label="최근 1년 매매 거래 건수",
        percentile_enabled=False,
        ranking_enabled=False,
    ),
}
